# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb8b640741d6ca2423507439799d4f82827b830388cd50b75eba51d5869de1ffc1b8079238d6eeb5ac025a16a57ec93335d4c6b05be93b83f0878190c2b97213

test:
  secret_key_base: 2ced0b378e24798e06392b670818644f7ae89d48a07560ab378038c8aacaff47a672cd7af608b0d778a0bf9e7f57ff428165c147953f80c34a9a6f02b044614b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
